version: "3.4"

networks:
  monitoring:

services:
  minitweetapi:
    image: minitweetapi
    container_name: minitwit
    build:
      context: ./MinitweetApi
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks: 
      - monitoring

  minitwitfrontend:
    image: minitwitfrontend
    build:
      context: ./MinitwitFrontend/MinitwitFrontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
    networks:
      - monitoring
      
