version: "3.4"

networks:
  minitwitnetwork:
    driver: bridge

services:
  minitweetapi:
    image: minitweetapi
    container_name: apicontainer
    env_file:
      - .env
    build:
      context: ./MinitweetApi
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - minitwitnetwork

  minitwitfrontend:
    image: minitwitfrontend
    build:
      context: ./MinitwitFrontend/MinitwitFrontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - minitwitnetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - minitwitnetwork

  grafana:
    image: grafana/grafana:4.5.2
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - minitwitnetwork

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - minitwitnetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - minitwitnetwork

volumes:
  elasticsearch-data:
  grafana-storage:
