version: "3.4"

networks:
  minitwitnetwork:

services:
  minitweetapi:
    image: registry.digitalocean.com/devopsitu/minitwitapi:latest
    container_name: apicontainer
    env_file:
      - .env
    ports:
      - "8000:80"
    networks:
      - minitwitnetwork

  minitwitfrontend:
    image: registry.digitalocean.com/devopsitu/minitwitfrontend:latest
    ports:
      - "5000:80"
    networks:
      - minitwitnetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - minitwitnetwork

  grafana:
    image: grafana/grafana:4.5.2
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - minitwitnetwork

volumes:
  grafana-storage:
