version: '3.4'

services:
  minitweetapi:
    image: ${DOCKER_REGISTRY-}minitweetapi
    build:
      context: .
      dockerfile: MinitweetApi/Dockerfile
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
        
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"