version: "3.4"

services:
  minitweetapi:
    image: registry.digitalocean.com/devopsitu/minitwitapi:latest
    env_file:
      - .env
    ports:
      - "8000:80"

  minitwitfrontend:
    image: registry.digitalocean.com/devopsitu/minitwitfrontend:latest
    ports:
      - "5000:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
