// <auto-generated />
using MInitweetApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MInitweetApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220209173332_new names")]
    partial class newnames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MInitweetApi.Models.Follower", b =>
                {
                    b.Property<int>("who_id")
                        .HasColumnType("integer");

                    b.Property<int>("whom_id")
                        .HasColumnType("integer");

                    b.ToTable("Follower");
                });

            modelBuilder.Entity("MInitweetApi.Models.Message", b =>
                {
                    b.Property<int>("message_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("message_Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("integer");

                    b.Property<int>("flagged")
                        .HasColumnType("integer");

                    b.Property<int>("pub_date")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("message_Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MInitweetApi.Models.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pw_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
