
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 0 * * 0,3'

name: Auto Release Twice a week

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Date
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.MY_DATE }}
          release_name: Release ${{ github.ref }}
          body: |
            Autorelease triggered
          draft: false
          prerelease: false
