name: Deploy to Digital Ocean
on:
  push:
    branches:
      - main
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Docker (login)
        run: doctl registry login
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/devopsitu/minitwitapi:latest
