name: Deploy to Digital Ocean
on:
  push:
    branches:
      - main
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__myDb1: ${{ secrets.DBCONSTRING }}
    steps:
      - uses: actions/checkout@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Docker (login)
        run: doctl registry login
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:MinitweetApi"
          push: true
          tags: registry.digitalocean.com/devopsitu/minitwitapi:latest
      - name: Docker pull
        uses: appleboy/ssh-action@master
        with:
          host: "68.183.67.47"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: docker pull registry.digitalocean.com/devopsitu/minitwitapi:latest
      - name: Docker stop all
        uses: appleboy/ssh-action@master
        with:
          host: "68.183.67.47"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: docker stop $(docker ps -q) || true
      - name: Docker remove all
        uses: appleboy/ssh-action@master
        with:
          host: "68.183.67.47"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: docker rm $(docker ps -a -q) || true
      - name: Docker run
        uses: appleboy/ssh-action@master
        with:
          host: "68.183.67.47"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: docker run -d -p 8000:80 --name minitwitapi registry.digitalocean.com/devopsitu/minitwitapi:latest
