name: Build LaTeX document
on: 
  workflow_dispatch
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd ./report
            pdflatex -output-directory build main.tex 

      - name: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          rm -f report/build/main.pdf
          cp report/main.pdf report/build/main.pdf
          git add report/build/main.pdf
          git commit -m "Generated PDF"
          git push
